import { ThemeProvider } from "./component/ThemeContext";
import "./globals.css";

export const metadata = {
  title: "Valenthuy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#ea50fb] overflow-hidden`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
